[package]
name = "schraper"
version = "0.1.0"
edition = "2024"

[dependencies]
scraper = "0.23"
rust_xlsxwriter = "0.85"
reqwest = { version = "0.12", features = ["blocking"] }
urlencoding = "2"
clap = { version = "4.5", features = ["cargo"] }
